### ISSUE TITLE
Support field validation

### ISSUE THREAD

**Issue by ejball** [FacilityApi/Facility#27]
We could use the `[validate]` attribute to request validation on fields. We could use concepts from Open API / JSON Schema.

* `string`, `bytes`: `[validate(minLength: 1, maxLength: 191, pattern: 'regex')]`
* `double`, etc.: `[validate(exclusiveMinimum: 0, maximum: 100)]`
* arrays, maps: `[validate(minItems: 1, maxItems: 10)]`
* enums: `[validate]` indicates that the string must be a valid enum value; could apply attribute to `enum` type for automatic use in all fields.

Validation applies to values of arrays, maps, and results where appropriate.

We could get more creative with syntax.

* `[validate(length: 1-91, regex: '^[a-z]+$')]`
* `[validate(length: 1+)]`
* `[validate(range: '(0-100]')]`
* `[validate(count: 1-10)]`

**Comment by jzbrooks** [comment]
Would you be interested in a PR for this @ejball?

It appears that the project is positioned to validate the `[validate]` attribute by field kind in the HTTP layer since that layer already makes substantial use of `ServiceInfo.GetFieldType`.

I propose string validation only contain a regular expression, since they can encode sizes implicitly. Errors might be unintuitive if the regular expression and length constraints disagree.

Several languages (JS, Kotlin, Rust, Swift, etc) have range syntax that could be leveraged. The down side is none of them agree syntactically around inclusive/exclusive extremes, but I think the general syntax would be familiar to many. The upshot is the same syntax could be used in multiple contexts

double, etc 
`[validate(in: 0..)]` - positive
`[validate(in: 0..9)]` - 0-9 inclusive
arrays, maps:
`[validate(count: 1..)]` - at least one element
`[validate(count: 1..9)]` - 1-9 elements inclusive

**Comment by ejball** [comment]
> Would you be interested in a PR for this

Sure, if you would use it, @jzbrooks! I've barely used `required` so I've not been tempted by more complex validation.

> validate the `[validate]` attribute by field kind in the HTTP layer

I'm not sure what you mean by this. In FacilityCSharp, each DTO has a `Validate` virtual method. I expect that would be used, and something like it in other languages.

> propose string validation only contain a regular expression

I disagree. OpenAPI seems like a good minimum standard for validation. It makes sense to support whatever it supports. It seems like setting a maximum length would be fairly common, and I wouldn't want that to have to be `^.{,100}$`.

> none of them agree syntactically around inclusive/exclusive extremes

I'm not excited the `..` syntax for this reason, but maybe it's still our best option. Otherwise, simple attributes seem fine to me, e.g. `minCount`, `maxCount`, `minLength`, `maxLength`, `minValue`, `maxValue`.

**Comment by jzbrooks** [comment]
> I'm not sure what you mean by this. In FacilityCSharp, each DTO has a Validate virtual method. I expect that would be used, and something like it in other languages.

I was thinking the FSD parser would fail, say, `[validate(minLength: 10)]` on a `double` field. So the ServiceFieldKind is required for appropriate validation. Then down the line a little bit FacilityCSharp would generate the actual validation code.

> It makes sense to support whatever it supports. 

Are similar semantics important to you? Should we handle discrepancies the same way? i.e. `[validate(maxLength: 100, pattern: '^.{,50}$']` If so, I can figure out what OpenAPI does in those situations.

> Otherwise, simple attributes seem fine to me, e.g. minCount, maxCount, minLength, maxLength, minValue, maxValue.

Maybe the burden of proof of value lies on range syntax, then. `-` has the same ambiguity problem around extremes in the absence of interval notation. For many, interval notation would require a refresher anyway, which isn't much different from learning the semantics of a `..` syntax. They'd both require looking at the docs.

I find a range to be a lot nicer looking, but that's certainly just a personal preference. The more explicit attribute style makes sense to me.

**Comment by ejball** [comment]
> I was thinking the FSD parser would fail, say, `[validate(minLength: 10)]` on a double field.

Agreed.

> I can figure out what OpenAPI does in those situations.

Surely it fails if either condition fails.

> I find a range to be a lot nicer looking

I agree, and I've warmed to it a bit. If you'd rather support `count`, `length`, and `value` with inclusive `..` ranges, I have no objection.
